name = "Paper Chan Optimized"
author = "mja00"
version = "1.1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c666c0a0ba2469684536963ae9f504678cbfe3eaa263108669bb8cd17cc6db73"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19.3"]
