name = "Kami Chan Optimized"
author = "mja00"
version = "1.3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de8229914d061f8730bf4f36f5ac4b7b99660b60e713452cd04f2728d3035ea2"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19.3"]
