name = "Kami Chan Optimized"
author = "mja00"
version = "1.3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0d8aa3b2b448e2dc6a0ba1caca44eefd87790fffff871e954791f32d724bd4c"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19.3"]
