name = "Kami Chan Optimized"
author = "mja00"
version = "2.0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1bc26bd686fcff765f4662e060bd4eb933d7c61e2e9f8f588face44069b11b1"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
