name = "Paper Chan Optimized"
author = "mja00"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "824bfdb921da532f25b2675e7a925d3145ba1ec6edd17a041a1d6c95479d230c"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19.3"]
